### ISSUE TITLE
Adding GitHub Actions

### ISSUE THREAD

**Issue by szabgab** [robrwo/Catalyst-Plugin-Static-File#1]
I am using the [CPAN Digger](https://cpan-digger.perlmaven.com/) to monitor uploads to CPAN and to find distributions that don't have CI setup. As I can see only a few of [your distributions](https://cpan-digger.perlmaven.com/author/RRWO) have CI, but those few have  GitHub Actions.

Would you be interested in receiving pull-requests to this and your other distributions adding GitHub Actions?

**Comment by robrwo** [comment]
Thank you for the suggestion.

However, I don't really see it as a priority. You submitted actions for some of my other distributions a while back (which I appreciate), but I received a lot of noisy notifications about them (especially random test failures that seemed to be related to prereqs on Windows for older Perls, and not the module itself).

The tests were eventually disabled automatically, as I wasn't pushing changes to their repos as often.

I'm also sceptical about how worthwhile these tests are. I don't think most distributions merit separate tests for Windows vs Linux vs Mac. I also don't think they need to be tested daily.

(The more interesting test failures seem to come from CPAN Testers where people are using older versions of prereqs or other unusual setups.)

Unless a distribution is widely used, I don't think it justifies the CPU cycles (and energy use which means burning carbon).

**Comment by szabgab** [comment]
It's a pity you did not tag me on those failures, we could have figured out a better way to use the CI.

Specifically these days I usually only configure the CI to be executed on push and pull-request and not with a scheduler.
They can also be disabled on older versions of perl on Windows.
